import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./QueryProvider";
import { CustomHeader } from "../components/CustomHeader";
import { CustomFooter } from "../components/CustomFooter";
import { Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Veneza Investimentos",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "600", "800"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <main className="flex flex-col h-screen">
            <CustomHeader />
            <div className={`${montserrat.variable}  mt-[98px]`}>
              {children}
            </div>
            <CustomFooter />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
